name: ECO_Vishnu_mocks_create

channels:
  - defaults
  - astropy
  - conda-forge

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas>=0.19.0
  - scipy
  - seaborn>=0.8.1
  - scikit-learn>=0.19.1
  - sphinx
  - halotools
  - pip
  - pip:
    - GitPython
    - progressbar2
    - sphinx_rtd_theme
    - tqdm
    - cosmo-utils
    - configparser
